name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    -  jjwebphpsymfony/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: CompileAndCheck
    displayName: Compile and check code
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: composer install
        workingDirectory: 'jjwebphpsymphony'
      displayName: 'Compose install'
    - task: ArchiveFiles@1
      displayName: 'Archive files'
      inputs:
        rootFolder: jjwebphpsymphony/
        includeRootFolder: false
        archiveType: zip
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      
#- stage: DeployTEST
#  displayName: Deploy to TEST
#  dependsOn: Build

