name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    -  jjwebphpsymphony/*

pool:
  vmImage: 'ubuntu-latest'

variables:
    subscription: 'jjdevteamproject-jjazure-web-php'

stages:
- stage: Build
  jobs:
  - job: CompileAndCheck
    displayName: Compile and check code
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: composer install
        workingDirectory: 'jjwebphpsymphony'
      displayName: 'Compose install'
    - task: ArchiveFiles@1
      displayName: 'Archive files'
      inputs:
        rootFolder: jjwebphpsymphony/
        includeRootFolder: false
        archiveType: default
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      
- stage: DeployTEST
  displayName: Deploy to TEST
  dependsOn: Build
  jobs:
    - deployment: DeployTESTWEBAPP
      displayName: Deploy to Azure Web App
      environment: 'jjphp-TEST'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  artifact: drop
                  path: $(Pipeline.Workspace)/drop
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy Azure App Service'
                inputs:
                  azureSubscription: $(subscription)
                  appType: webAppLinux
                  WebAppName: jjphp
                  packageForLinux: $(Pipeline.Workspace)/drop/**/*.zip
                  RuntimeStack: 'PHP|7.4'
                  ScriptType: 'Inline Script'
                  InlineScript: cp /home/site/wwwroot/.htaccess.azure /home/site/wwwroot/.htaccess         