app_insights_php:
  enabled: true
  gzip_enabled: false
  instrumentation_key: "cd6188be-c900-4003-97fb-304858a7db29" #"%env(MICROSOFT_APP_INSIGHTS_INTRUMENTATION_KEY)%"
  exceptions:
    enabled: true
    ignored_exceptions:
      - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
  dependencies:
    enabled: true
  requests:
    enabled: true
  traces:
    enabled: true
  doctrine:
    track_dependency: true
