doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        #driver: pdo_mysql
        #host: jjtestmysql.mysql.database.azure.com
        driver: mysqli
        host: p:jjtestmariadb.mariadb.database.azure.com
        port: 3306
        dbname: jjdb
        #user: jj@jjtestmysql
        user: jj@jjtestmariadb
        password: Azure-12345
        charset: UTF8
        server_version: mariadb-10.3.0

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
