name: jjwebphpsymphony-cicd

on:
  workflow_dispatch:
          
  push:
    branches: [ master ]
    paths: ./jjwebphpsymphony

env:
  AZURE_WEBAPP_NAME: jjphp

jobs:  
     
  build-and-deploy:
    env:
      working-directory: ./jjwebphpsymphony
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Composer Install
      run: composer install
      working-directory: ./jjwebphpsymphony
    
#    - name: 'Deploy to Azure WebApp'
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: ${{ env.AZURE_WEBAPP_NAME }}
#        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#        package: .
    
